apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: expense-tracker
  name: expense-tracker-deployment
  labels:
    app: expense-tracker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-tracker-deployment
  template:
    metadata:
      labels:
        app: expense-tracker-deployment
    spec:
      containers:
      - name: expense-tracker-deployment
        image: nischalstha/expense_tracker_web
        # command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
        command: ["sh", "/code/docker-entrypoint.sh" ]
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: expense-tracker-secrets
        resources:
          requests:
            memory: "450Mi"
            cpu: "0.45"
          limits:
            memory: "500Mi"
            cpu: "0.5"

# ---

# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: base-django-autoscaler
#   namespace: base-django
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: expense-tracker-deployment
#   minReplicas: 1
#   maxReplicas: 10
#   targetCPUUtilizationPercentage: 50