apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: base-django
  name: base-django-deployment
  labels:
    app: base-django-deployment
spec:
  # replicas: 3
  selector:
    matchLabels:
      app: base-django-deployment
  template:
    metadata:
      labels:
        app: base-django-deployment
    spec:
      containers:
      - name: base-django-deployment
        image: nischalstha/django_base_web:latest
        command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: base-django-secrets
        resources:
          requests:
            memory: "450Mi"
            cpu: "900m"
          limits:
            memory: "500Mi"
            cpu: "1000m"

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: base-django-autoscaler
  namespace: base-django
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: base-django-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50