apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: base-django-ingress
  namespace: base-django
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: admin.django.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: django-base-service
            port:
              number: 8000
