apiVersion: v1
kind: ConfigMap
metadata:
  name: expense-tracker-nginx-conf
  namespace: expense-tracker
data:
  nginx.conf: |
    user nginx;
    worker_processes  3;
    error_log  /var/log/nginx/error.log;
    events {
      worker_connections  10240;
    }
    http {
      log_format  main
              'remote_addr:$remote_addr\t'
              'time_local:$time_local\t'
              'method:$request_method\t'
              'uri:$request_uri\t'
              'host:$host\t'
              'status:$status\t'
              'bytes_sent:$body_bytes_sent\t'
              'referer:$http_referer\t'
              'useragent:$http_user_agent\t'
              'forwardedfor:$http_x_forwarded_for\t'
              'request_time:$request_time';
      access_log	/var/log/nginx/access.log main;
      server {
          listen       80;
          server_name  expensetracker.com;
          location / {
              root   /opt/expense-tracker/;
              index  index.html index.htm;
              try_files $uri $uri/ /index.html;
          }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: expense-tracker
  name: expense-tracker-nginx-frontend
  labels:
    app: expense-tracker-nginx-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-tracker-nginx-frontend
  template:
    metadata:
      labels:
        app: expense-tracker-nginx-frontend
    spec:
      containers:
      - name: expense-tracker-nginx-frontend
        image: nischalstha/expense-tracker-frontend
        resources:
            requests:
              memory: "200Mi"
              cpu: "0.2"
            limits:
              memory: "250Mi"
              cpu: "0.3"
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx # mount nginx-conf volumn to /etc/nginx
          readOnly: true
          name: nginx-conf-volume
      volumes:
      - name: nginx-conf-volume
        configMap:
          name: expense-tracker-nginx-conf # place ConfigMap `nginx-conf` on /etc/nginx
          items:
            - key: nginx.conf
              path: nginx.conf

---
apiVersion: v1
kind: Service
metadata:
  name: expense-tracker-frontend-service
  namespace: expense-tracker
spec:
  # type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 80
  selector:
    app: expense-tracker-nginx-frontend
