
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-config-maps
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  # storageClassName: nfs-server-1
  nfs:
    server: 3.111.157.23
    path: "/srv/ElasticVolume/nginx/site-enabled"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-sites
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  # storageClassName: nfs-server-1-sites
  nfs:
    server: 3.111.157.23
    path: "/srv/ElasticVolume/nginx/static"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-config-claim
  namespace: expense-tracker
spec:
  claimRef: null
  accessModes:
    - ReadWriteMany
  # storageClassName: nfs-server-1
  resources:
    requests:
      storage: 200Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-sites-claim
  namespace: expense-tracker
spec:
  claimRef: null
  accessModes:
    - ReadWriteMany
  # storageClassName: nfs-server-1-sites
  resources:
    requests:
      storage: 200Mi